app = "ai-driven-proactive-maintenance-for-warehouse-temperature-monitoring"

[deploy]
  release_command = "flask run"  # This may need to be adjusted depending on how your app is structured

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true

[[services]]
  internal_port = 8080            # The port your Flask app listens on
  protocol = "tcp"

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[services.ports]]
  port = 80                       # The port that will be publicly accessible
  handlers = ["http"]
