app = "ai-driven-proactive-maintenance-for-warehouse-temperature-monitoring"

[deploy]
  release_command = "flask run"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[services.ports]]
  port = 80
  handlers = ["http"]
