name: Flask Application Deployment

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    # The type of machine the workflow runs on
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the application tests (Optional)
    - name: Run tests
      run: |
        pytest  # Assuming you have tests in your project

    # Step 5: Deploy to the cloud or hosting service
    # If you're deploying to a service like Heroku, include deployment steps here
    # Example for Heroku or Render would follow here.
